version: '3.4'

services:
  aspnet21-log:
    image: aspnet21log
    build:
      context: .
      dockerfile: src/AspNet21-Log/Dockerfile
    depends_on:
      - elk
  elk:
    image: sebp/elk
    ports:
      - "5601:5601"
      - "9200:9200"